### ISSUE TITLE
if in return check

### ISSUE THREAD

**Issue by Whimsyduke** [Talv/plaxtony#3]
`int func()
{
    if(true)
    {
        if(true)
        {
            return 0;
        }
        else
        {
            return 1;
        }
    }
    else
    {
        return 2;
    }
}`

Get a error with the message "Expected return statement"

**Comment by Talv** [comment]
Yeah.. current method of checking for `return` is not quite reliable :|
I guess it's time to roll out a new release soon, it's been almost 2 months. But only 3 bugs found - something I'm glad about.
